### ISSUE TITLE
Not able to import in Eclipse

### ISSUE THREAD

**Issue by TheCodeCache** [MichalGoly/MusicStore#1]
I know this project is written using netbeans.. but I wanted to import into eclipse, which is failing.. any fixes..

**Comment by MichalGoly** [comment]
Hi @softmanu, I wrote this project before I knew of the existence of Gradle, or even Maven. I've had a quick google and it seems to be possible to import Netbeans projects into Eclipse by importing distribution `war` files. 

See the stackoverflow answer here: https://stackoverflow.com/a/31875864

I have just uploaded the `war` file [here](https://github.com/MichalGoly/MusicStore/releases/tag/1.0.0). Let me know if it worked and I will update the project's README with Eclipse instructions.
